
spring:
  #??????
#  resources:
#    #???????????????
#    add-mappings: true
#    cache:
#      cachecontrol:
#        #??????????
#        max-age: 3600
#    chain:
#      #?????????????
#      cache: true
#      #??????????
#      enabled: true
#      #???????gzip?brotil????????
#      compressed: true
#      #??h5?????????
#      html-application-cache: true
#    static-locations: classpath:/static/
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        max-age: 3600
      chain:
        cache: true
        enabled: true
        compressed: true
        html-application-cache: true
      static-locations: classpath:/static/


  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hknmysql
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #?????????????10??
      idle-timeout: 600000
      #????????10
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #?????????0?????????1800000?30???
      max-lifetime: 1800000
      #?????????30000?30??
      connection-timeout: 3000
      #?????????????
      connection-test-query: SELECT 1

#  redis:
#    #        password: hknredis
#    requirepass: hknredis
#    database: 0
#    timeout: 10000ms
#    lettuce:
#      pool:
#        #????? ??8
#        max-active: 8
#        #????????
#        max-wait: 1000ms
#        #?????????8
#        max-idle: 200
#        min-idle: 5



  rabbitmq:
    #???
    host: 127.0.0.1
    #???
    username: itcast
    #??
    password: 123123
    #????
    virtual-host: /
    #??
    port: 5672
    listener:
      simple:
        #???????
        concurrency: 10
        #???????
        max-concurrency: 10
        #???????????????????????????
        prefetch: 1
        #?????????
        auto-startup: true
        #??????????
        default-requeue-rejected: true
    template:
      retry:
        #???????false
        enabled: true
        #???????1000ms
        initial-interval: 1000ms
        #?????????3?
        max-attempts: 3
        #????????
        max-interval: 10000ms
        #???????????2?0  ???10s ????20s ????40s
        multiplier: 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      requirepass: hknredis
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          #????? ??8
          max-active: 8
          #????????
          max-wait: 1000ms
          #?????????8
          max-idle: 200
          min-idle: 5
      password: hknredis


#mybatis-plus
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.seckill


mybatis-plus:
#mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.sekilldemo.mapper: debug
    logging:
      level:
        org:
          thymeleaf=DEBUG: