
spring:
  #??????
#  resources:
#    #???????????????
#    add-mappings: true
#    cache:
#      cachecontrol:
#        #??????????
#        max-age: 3600
#    chain:
#      #?????????????
#      cache: true
#      #??????????
#      enabled: true
#      #???????gzip?brotil????????
#      compressed: true
#      #??h5?????????
#      html-application-cache: true
#    static-locations: classpath:/static/
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        max-age: 3600
      chain:
        cache: true
        enabled: true
        compressed: true
        html-application-cache: true
      static-locations: classpath:/static/


  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hknmysql
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #?????????????10??
      idle-timeout: 600000
      #????????10
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #?????????0?????????1800000?30???
      max-lifetime: 1800000
      #?????????30000?30??
      connection-timeout: 3000
      #?????????????
      connection-test-query: SELECT 1

#  redis:
#    #        password: hknredis
#    requirepass: hknredis
#    database: 0
#    timeout: 10000ms
#    lettuce:
#      pool:
#        #????? ??8
#        max-active: 8
#        #????????
#        max-wait: 1000ms
#        #?????????8
#        max-idle: 200
#        min-idle: 5



  #RabbitMQ
  rabbitmq:
    #服务器
    host: 127.0.0.1
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动是默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #最大重试间隔时间
        max-interval: 10000ms
        #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
        multiplier: 1

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      requirepass: hknredis
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          #????? ??8
          max-active: 8
          #????????
          max-wait: 1000ms
          #?????????8
          max-idle: 200
          min-idle: 5
      password: hknredis


#mybatis-plus
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.seckill


mybatis-plus:
#mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.sekilldemo.mapper: debug
    logging:
      level:
        org:
          thymeleaf=DEBUG: